# Generated by Django 4.2.7 on 2023-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('sex', models.FloatField()),
                ('bmi', models.FloatField()),
                ('children', models.FloatField()),
                ('smoker', models.FloatField()),
                ('region', models.FloatField()),
                ('charges', models.FloatField()),
            ],
        ),
    ]
